version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: limoome
    ports:
      - '5000:5000'
    depends_on:
      - redis
      - database
    networks:
      - app-net
    environment:
      - PORT=5000
      - DB_PATH=./data/limoome.sq3
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  database:
    image: alpine
    volumes:
      - ./data:/data
    networks:
      - app-net

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'
    networks:
      - app-net

networks:
  app-net:
